#!/usr/bin/env python3
"""Embed the shared Rime payload files into a C header for the Linux build."""
import os
import sys


def emit(name: str, data: bytes) -> str:
    lines = [f"static const char {name}_data[] = {{"]
    chunk = []
    for index, byte in enumerate(data):
        chunk.append(str(byte))
        if len(chunk) == 20:
            lines.append("  " + ",".join(chunk) + ",")
            chunk = []
    if chunk:
        lines.append("  " + ",".join(chunk) + ",")
    lines.append("};")
    lines.append(f"static const unsigned long {name}_size = {len(data)}UL;")
    return "\n".join(lines)


def main() -> int:
    config_path, presets_path, out_path = sys.argv[1], sys.argv[2], sys.argv[3]
    config = open(config_path, "rb").read()
    presets = open(presets_path, "rb").read()

    with open(out_path, "w", encoding="utf-8") as handle:
        handle.write("/* Generated by tools/embed.py — do not edit. */\n")
        handle.write("#ifndef SQUIRREL_PAYLOAD_H\n#define SQUIRREL_PAYLOAD_H\n\n")
        handle.write(emit("default_custom_yaml", config))
        handle.write("\n\n")
        handle.write(emit("presets_json", presets))
        handle.write("\n\n")
        handle.write(
            "static const char *default_custom_yaml(unsigned long *length) {\n"
            "  if (length) *length = default_custom_yaml_size;\n"
            "  return default_custom_yaml_data;\n"
            "}\n\n"
            "static const char *presets_json(unsigned long *length) {\n"
            "  if (length) *length = presets_json_size;\n"
            "  return presets_json_data;\n"
            "}\n\n"
        )
        handle.write("#endif /* SQUIRREL_PAYLOAD_H */\n")
    print(f"payload embedded: {len(config)} + {len(presets)} bytes -> {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
